# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnLibro.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_vtnLibro(object):
    def setupUi(self, vtnLibro):
        if not vtnLibro.objectName():
            vtnLibro.setObjectName(u"vtnLibro")
        vtnLibro.resize(506, 389)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        vtnLibro.setFont(font)
        self.centralwidget = QWidget(vtnLibro)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lblCodigo = QLabel(self.centralwidget)
        self.lblCodigo.setObjectName(u"lblCodigo")
        self.lblCodigo.setGeometry(QRect(90, 30, 71, 20))
        font1 = QFont()
        font1.setFamilies([u"Century Gothic"])
        font1.setPointSize(11)
        font1.setBold(True)
        self.lblCodigo.setFont(font1)
        self.lblNombre = QLabel(self.centralwidget)
        self.lblNombre.setObjectName(u"lblNombre")
        self.lblNombre.setGeometry(QRect(40, 90, 61, 16))
        self.lblNombre.setFont(font1)
        self.lblPrecio = QLabel(self.centralwidget)
        self.lblPrecio.setObjectName(u"lblPrecio")
        self.lblPrecio.setGeometry(QRect(40, 130, 61, 16))
        self.lblPrecio.setFont(font1)
        self.lblCantidad = QLabel(self.centralwidget)
        self.lblCantidad.setObjectName(u"lblCantidad")
        self.lblCantidad.setGeometry(QRect(40, 170, 81, 16))
        self.lblCantidad.setFont(font1)
        self.lblAutor = QLabel(self.centralwidget)
        self.lblAutor.setObjectName(u"lblAutor")
        self.lblAutor.setGeometry(QRect(40, 210, 61, 16))
        self.lblAutor.setFont(font1)
        self.lblEdicion = QLabel(self.centralwidget)
        self.lblEdicion.setObjectName(u"lblEdicion")
        self.lblEdicion.setGeometry(QRect(40, 260, 61, 16))
        self.lblEdicion.setFont(font1)
        self.lblIsbn = QLabel(self.centralwidget)
        self.lblIsbn.setObjectName(u"lblIsbn")
        self.lblIsbn.setGeometry(QRect(290, 170, 61, 16))
        self.lblIsbn.setFont(font1)
        self.txtCodigo = QLineEdit(self.centralwidget)
        self.txtCodigo.setObjectName(u"txtCodigo")
        self.txtCodigo.setGeometry(QRect(160, 30, 191, 21))
        self.txtCodigo.setMaxLength(10)
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(120, 90, 251, 21))
        self.txtNombre.setMaxLength(50)
        self.txtIsbn = QLineEdit(self.centralwidget)
        self.txtIsbn.setObjectName(u"txtIsbn")
        self.txtIsbn.setGeometry(QRect(360, 170, 121, 20))
        self.txtIsbn.setMaxLength(10)
        self.txtCantidad = QLineEdit(self.centralwidget)
        self.txtCantidad.setObjectName(u"txtCantidad")
        self.txtCantidad.setGeometry(QRect(120, 170, 121, 21))
        self.txtCantidad.setMaxLength(1000)
        self.txtAutor = QLineEdit(self.centralwidget)
        self.txtAutor.setObjectName(u"txtAutor")
        self.txtAutor.setGeometry(QRect(120, 210, 261, 21))
        self.txtAutor.setMaxLength(50)
        self.txtEdicion = QLineEdit(self.centralwidget)
        self.txtEdicion.setObjectName(u"txtEdicion")
        self.txtEdicion.setGeometry(QRect(120, 260, 261, 21))
        self.txtEdicion.setMaxLength(50)
        self.btnNuevo = QPushButton(self.centralwidget)
        self.btnNuevo.setObjectName(u"btnNuevo")
        self.btnNuevo.setGeometry(QRect(10, 320, 111, 31))
        self.btnNuevo.setFont(font)
        self.btnNuevo.setMouseTracking(False)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.btnNuevo.setIcon(icon)
        self.btnLimpiar = QPushButton(self.centralwidget)
        self.btnLimpiar.setObjectName(u"btnLimpiar")
        self.btnLimpiar.setGeometry(QRect(390, 320, 111, 31))
        self.btnLimpiar.setFont(font)
        self.btnLibrobuscar = QPushButton(self.centralwidget)
        self.btnLibrobuscar.setObjectName(u"btnLibrobuscar")
        self.btnLibrobuscar.setGeometry(QRect(360, 20, 71, 41))
        self.btnLibrobuscar.setFont(font)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditFind))
        self.btnLibrobuscar.setIcon(icon1)
        self.btnBorrar = QPushButton(self.centralwidget)
        self.btnBorrar.setObjectName(u"btnBorrar")
        self.btnBorrar.setGeometry(QRect(270, 320, 111, 31))
        self.btnBorrar.setFont(font)
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditDelete))
        self.btnBorrar.setIcon(icon2)
        self.btnActualizar = QPushButton(self.centralwidget)
        self.btnActualizar.setObjectName(u"btnActualizar")
        self.btnActualizar.setGeometry(QRect(140, 320, 111, 31))
        self.btnActualizar.setFont(font)
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.SyncSynchronizing))
        self.btnActualizar.setIcon(icon3)
        self.txtPrecio = QLineEdit(self.centralwidget)
        self.txtPrecio.setObjectName(u"txtPrecio")
        self.txtPrecio.setGeometry(QRect(120, 130, 241, 21))
        self.txtPrecio.setMaxLength(5)
        vtnLibro.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(vtnLibro)
        self.statusbar.setObjectName(u"statusbar")
        vtnLibro.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtCodigo, self.txtNombre)
        QWidget.setTabOrder(self.txtNombre, self.txtPrecio)
        QWidget.setTabOrder(self.txtPrecio, self.txtCantidad)
        QWidget.setTabOrder(self.txtCantidad, self.txtIsbn)
        QWidget.setTabOrder(self.txtIsbn, self.txtAutor)
        QWidget.setTabOrder(self.txtAutor, self.txtEdicion)
        QWidget.setTabOrder(self.txtEdicion, self.btnNuevo)
        QWidget.setTabOrder(self.btnNuevo, self.btnActualizar)
        QWidget.setTabOrder(self.btnActualizar, self.btnBorrar)
        QWidget.setTabOrder(self.btnBorrar, self.btnLimpiar)
        QWidget.setTabOrder(self.btnLimpiar, self.btnLibrobuscar)

        self.retranslateUi(vtnLibro)

        QMetaObject.connectSlotsByName(vtnLibro)
    # setupUi

    def retranslateUi(self, vtnLibro):
        vtnLibro.setWindowTitle(QCoreApplication.translate("vtnLibro", u"Sistema Invetario Libro", None))
        self.lblCodigo.setText(QCoreApplication.translate("vtnLibro", u"Codigo:", None))
        self.lblNombre.setText(QCoreApplication.translate("vtnLibro", u"Nombre:", None))
        self.lblPrecio.setText(QCoreApplication.translate("vtnLibro", u"Precio:", None))
        self.lblCantidad.setText(QCoreApplication.translate("vtnLibro", u"Cantidad:", None))
        self.lblAutor.setText(QCoreApplication.translate("vtnLibro", u"Autor:", None))
        self.lblEdicion.setText(QCoreApplication.translate("vtnLibro", u"Edici\u00f3n:", None))
        self.lblIsbn.setText(QCoreApplication.translate("vtnLibro", u"ISBN:", None))
        self.btnNuevo.setText(QCoreApplication.translate("vtnLibro", u"NUEVO", None))
        self.btnLimpiar.setText(QCoreApplication.translate("vtnLibro", u"LIMPIAR", None))
        self.btnLibrobuscar.setText("")
        self.btnBorrar.setText(QCoreApplication.translate("vtnLibro", u"BORRAR", None))
        self.btnActualizar.setText(QCoreApplication.translate("vtnLibro", u"ACTUALIZAR", None))
    # retranslateUi

